In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))

train_df = train_df.drop(['Unnamed: 0', 'index'], axis='columns')
train_df.head()

# train_df['loan_status'].value_counts()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,dti,delinq_2yrs,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,13375.0,0.1797,483.34,MORTGAGE,223000.0,Not Verified,low_risk,n,29.99,0.0,...,100.0,50.0,0.0,0.0,577150.0,122018.0,32000.0,170200.0,N,N
1,21000.0,0.1308,478.68,MORTGAGE,123000.0,Source Verified,low_risk,n,11.26,2.0,...,85.0,33.3,0.0,0.0,132750.0,27896.0,15900.0,35398.0,N,N
2,20000.0,0.1240,448.95,MORTGAGE,197000.0,Source Verified,low_risk,n,11.28,0.0,...,85.7,33.3,0.0,0.0,628160.0,114043.0,22600.0,90340.0,N,N
3,3000.0,0.1240,100.22,RENT,45000.0,Not Verified,low_risk,n,18.08,0.0,...,100.0,16.7,1.0,0.0,42006.0,20761.0,19900.0,15406.0,N,N
4,30000.0,0.1612,1056.49,MORTGAGE,133000.0,Source Verified,low_risk,n,27.77,0.0,...,100.0,66.7,0.0,0.0,283248.0,109056.0,79500.0,58778.0,N,N

In [3]:
test_df = test_df.drop(['Unnamed: 0', 'index'], axis='columns')
test_df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,dti,delinq_2yrs,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,40000.0,0.0819,814.70,MORTGAGE,140000.0,Not Verified,low_risk,n,19.75,0.0,...,97.7,0.0,0.0,0.0,527975.0,70914.0,74600.0,99475.0,N,N
1,6000.0,0.1524,208.70,RENT,55000.0,Not Verified,low_risk,n,11.52,2.0,...,66.7,0.0,0.0,0.0,34628.0,23460.0,5900.0,23628.0,N,N
2,3600.0,0.1695,128.27,RENT,42000.0,Not Verified,low_risk,n,6.74,0.0,...,100.0,0.0,0.0,0.0,23100.0,19183.0,7300.0,15000.0,N,N
3,20000.0,0.1524,478.33,RENT,100000.0,Not Verified,low_risk,n,12.13,0.0,...,100.0,50.0,0.0,0.0,56481.0,43817.0,13800.0,35981.0,N,N
4,3600.0,0.1240,120.27,RENT,50000.0,Not Verified,low_risk,n,16.08,0.0,...,100.0,25.0,0.0,0.0,45977.0,32448.0,21000.0,24977.0,N,N

In [4]:
# Convert categorical data to numeric and separate target feature for training data
dum_train = train_df.drop(['loan_status'], axis=1)
dum_train = pd.get_dummies(dum_train)

In [5]:
# Convert categorical data to numeric and separate target feature for testing data
dum_test = test_df.drop(['loan_status'], axis=1)
dum_test = pd.get_dummies(dum_test)

In [6]:
# find the missing variable/column by comparing the two dummy dfs
train_col = [x for x in dum_train.columns]

for col in dum_test:
    for x in train_col:
        if col == x:
            train_col.pop(train_col.index(x))

print(train_col)

['debt_settlement_flag_Y']

In [7]:
# add missing dummy variables to testing set

# the debt_settlment_flag_N values suggest that the debt_settlement_flag_Y values to be added should all be 0
dum_test['debt_settlement_flag_N'].value_counts()

# adding in the missing dummy variable column
dum_test['debt_settlement_flag_Y'] = 0
dum_test

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N,debt_settlement_flag_Y
0,40000.0,0.0819,814.70,140000.0,19.75,0.0,1.0,18.0,0.0,9471.0,...,0,1,0,1,1,0,1,0,1,0
1,6000.0,0.1524,208.70,55000.0,11.52,2.0,0.0,8.0,0.0,1280.0,...,0,1,0,1,1,0,1,0,1,0
2,3600.0,0.1695,128.27,42000.0,6.74,0.0,0.0,6.0,0.0,4757.0,...,0,1,0,1,1,0,1,0,1,0
3,20000.0,0.1524,478.33,100000.0,12.13,0.0,2.0,7.0,0.0,12731.0,...,0,1,0,1,1,0,1,0,1,0
4,3600.0,0.1240,120.27,50000.0,16.08,0.0,3.0,6.0,0.0,10413.0,...,0,1,0,1,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4697,30000.0,0.1240,673.42,140480.0,15.74,0.0,0.0,20.0,0.0,23215.0,...,0,1,1,0,1,0,1,0,1,0
4698,24000.0,0.0756,747.22,50000.0,26.81,0.0,0.0,9.0,0.0,459.0,...,0,1,0,1,1,0,1,0,1,0
4699,10000.0,0.2305,387.36,33000.0,38.51,0.0,2.0,7.0,0.0,6342.0,...,1,1,1,0,1,0,1,0,1,0
4700,8000.0,0.1862,205.86,38000.0,16.36,0.0,1.0,8.0,1.0,11636.0,...,0,1,0,1,1,0,1,0,1,0
4701,30000.0,0.2055,1123.34,180000.0,12.06,0.0,0.0,8.0,0.0,4771.0,...,0,1,1,0,1,0,1,0,1,0

In [8]:
# training on logistic regression vs. random forest

Prediction: Random forest may do better because the data is currently unscaled, which may affect logistic regression's score relative to that of random forest's.

In [9]:
# assign training data to x or y
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
X_train = dum_train
y_train = LabelEncoder().fit_transform(train_df['loan_status'])

In [10]:
# Train the Logistic Regression model on the unscaled data and print the model score
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression()
log_model.fit(X_train, y_train)

/Users/emilyye/opt/anaconda3/envs/PythonData/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [11]:
# define the testing x and y data
X_test = dum_test
y_test = LabelEncoder().fit_transform(test_df['loan_status'])

In [12]:
print(log_model.score(X_train, y_train))
log_model.score(X_test, y_test)

0.6511494252873563

0.5163760102084219

In [13]:
# Train a Random Forest Classifier model and print the model score
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=1, n_estimators=500)
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=500, random_state=1)

In [14]:
print(rf.score(X_train, y_train))
rf.score(X_test, y_test)

1.0

0.6433432581880051

Random forest did indeed do better with both the training and test data sets. My hypothesis is that the uneven data scales in the dataframes has caused logistic regression to underperform

In the following steps, where data is scaled before re-fitted into the models, I think logistic regression will see a relative jump in score, enough to surpass the score from using random forest. Random forest should not be affected too much by scaled data.

In [15]:
# Scale the data
from sklearn.preprocessing import StandardScaler as ss

scaler = ss().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_train_scaled

X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[ 2.20755943, -1.12001617,  1.0371484 , ..., -0.17149859,
         0.02026518, -0.02026518],
       [-1.11348584,  0.21833096, -1.01983876, ..., -0.17149859,
         0.02026518, -0.02026518],
       [-1.34791257,  0.54295132, -1.2928478 , ..., -0.17149859,
         0.02026518, -0.02026518],
       ...,
       [-0.72277464,  1.7009538 , -0.41340093, ..., -0.17149859,
         0.02026518, -0.02026518],
       [-0.91813024,  0.85997823, -1.02947877, ..., -0.17149859,
         0.02026518, -0.02026518],
       [ 1.23078141,  1.22636262,  2.08478621, ..., -0.17149859,
         0.02026518, -0.02026518]])

In [16]:
# Train the Logistic Regression model on the scaled data and print the model score

log_model.fit(X_train_scaled, y_train)
print(log_model.score(X_train_scaled, y_train))
log_model.score(X_test_scaled, y_test)

0.7078817733990148

/Users/emilyye/opt/anaconda3/envs/PythonData/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.767333049766057

In [17]:
# Train a Random Forest Classifier model on the scaled data and print the model score

rf.fit(X_train_scaled, y_train)
print(rf.score(X_train_scaled, y_train))
rf.score(X_test_scaled, y_test)

1.0

0.6420672054444917

My previous prediction turned out to be correct. The logistic regression approach became more effective -- even more effective than random forest -- once the data was scaled; random forest was not affected by much (though, in very exacting terms, its score when predicting test data dropped by ~0.001)